---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: openshift-gitops
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
